volumes:
  growing_me:
    name: growing_me
  
services:
  api:
    env_file: 
      - ".env"
    build:
      context: api
      dockerfile: Dockerfile.dev
    environment:
      CORS_HOST: http://localhost:5173
      MONGO_DB_URI: ${MONGO_DB_URI}
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_HOSTS: mongo:27017
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    env_file: 
      - ".env"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - growing_me:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URI}
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo