services:
  api:
    env_file: 
      - ./env/api.env
    build: ./api
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    env_file: 
      - ./env/mongo.env
    restart: always
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    env_file: 
      - ./env/mexpress.env
    ports:
      - 8081:8081
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo

volumes:
  data:
  
