volumes:
  mongo:

services:
  # ghi:
  #   build:
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "5173:5173"
  api:
    env_file: 
      - ".env"
    build:
      context: api
      dockerfile: Dockerfile.dev
    environment:
      CORS_HOST: http://localhost:5173
      MONGO_DB_URI: ${MONGO_DB_URI}
      SIGNING_KEY: ${SIGNING_KEY}
      WAIT_HOSTS: mongo:27017
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app

  mongo:
    image: mongo:latest
    env_file: 
      - ".env"
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    ports:
      - "6000:27017"
    volumes:
      - mongo:/data/db
