services:
  app:
    env_file:
      - ./env/app.env
    build: ./app
    environment:
      VITE_API_HOST: http://localhost:8000
      BASE_URL: http://localhost:4173
    ports:
      - "4173:4173"
    depends_on:
      - api

  api:
    env_file: 
      - ./env/api.env
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./api:/app

  mongodb:
    image: mongo
    env_file: 
      - ./env/mongo.env
    restart: always
    volumes:
      - growing_me:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    env_file: 
      - ./env/mexpress.env
    ports:
      - 8081:8081
    environment:
      WAIT_HOSTS: mongodb:27017
    depends_on:
      - mongodb

volumes:
  growing_me:
  
