name: FastAPI CI

on: 
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and Start Docker Containers
      run: | 
        docker-compose build
        docker-compose up -d

    - name: Run Tests
      run: docker-compose exec -T app pytest

    - name: Run Linter
      run: docker-compose exec -T app flake8 .

    - name: Check Formatting
      run: docker-compose exec -T app black --check .

    - name: Stop containers
      if: always()
      run: docker-compose down
